apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: weather-service
  namespace: distributed-tracing-example
spec:
  hosts:
  - "*"
  gateways:
    - istio-system/weather-service
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: weather-service
        port:
          number: {{ .Values.deployment.httpPortWeatherService }}