apiVersion: apps/v1
kind: Deployment
metadata:
  name: owm-service
  namespace: {{ .Values.deployment.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label }}
    spec:
      containers:
      - name: {{ .Values.deployment.containerNameOWMService }}
        image: {{ .Values.deployment.containerImageOWMService }}
        resources:
          requests:
            cpu: {{ .Values.deployment.requestCPU }}
            memory: {{ .Values.deployment.requestMemory }}
          limits:
            cpu: {{ .Values.deployment.limitCPU }}
            memory: {{ .Values.deployment.limitMemory }}
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: {{ .Values.deployment.httpPortOWMService }}
            protocol: TCP  
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.healthPath }}
            port: {{ .Values.deployment.httpPortOWMService }}
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.healthPath }}
            port: {{ .Values.deployment.httpPortOWMService}}
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
        env:
          - name: TRACER_ENDPOINT
            value: {{ .Values.deployment.tracerEndpoint }}
          - name: OWM_APP_ID
            value: {{ .Values.deployment.owmAppID }}
          - name: OWM_ADDR
            value: {{ .Values.deployment.owmHost }}
          - name: PORT
            value: "8082"
      restartPolicy: Always